### PR TITLE
[DO-29] New CloudFormation Lambda Creation Role.

### PR DESCRIPTION
**Pull request by sapiensantiquus**

### CODE REVIEW

**Comment by simplyadrian** [comment]
Awesome work here... Going to merge and give it a go.

**Comment by simplyadrian** [comment]
only thing I can think of to enhance this role at this time is to add the ability to create cloudwatch rules for scheduled events. maybe its a separate concern for another role but it would be nice to be able to signal the creation of a schedule from this role.

**Comment by sapiensantiquus** [comment]
@simplyadrian I didn't even bother with scheduled events, because you can't create event mappings for them with cloudformation.

**Comment by sapiensantiquus** [comment]
@simplyadrian  At the time I didn't think you could use CFN to target lambda functions. It looked like CFN was missing that capability, and documentation said you had to do it through the CLI or console. Now that I know I can, I will. I actually need it for what I'm working on.

**Comment by simplyadrian** [comment]
Yeah, I also discovered you can’t control versions from cloud formation last night.
Adrian Herrera
Systems Architect/ DevOps

SimplyAdrian | SimplyAdrian.io <https://www.linkedin.com/in/adrianherrera>
e simplyadrian@gmail | m 612.396.9576
Follow me on Twitter @simplyadrian

**Pull request merged**
